name: simple_breadcrumbs
description: "A small widget to implement breadcrumbs into a flutter app"
version: 0.0.1
homepage: https://www.lpickford.dev
repository: https://github.com/Contract16/simple_breadcrumbs
issue_tracker: https://github.com/Contract16/simple_breadcrumbs/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  uses-material-design: true
